# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest
variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
steps:
 task: BuildVariableTask@3
  inputs:
    buildmode: 'Prime'
    variable: 'count'
    mode: 'Autoincrement'
    usedefaultcreds: true
    usePSCore: False
    condition: and(succeeded(), eq(variables.isMain, 'true'))
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
  condition: and(succeeded(), eq(variables.isMain, 'true'))
- task: Maven@3
  inputs:
    mavenPomFile: 'my-app/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    mavenAuthenticateFeed: true
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    
